### ISSUE TITLE
Take care where you put an Console.Clear

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Hangman#11]
https://github.com/thirdiblind/Hangman/blob/684eeb326872cafb6a91c894ecfb2a28e8459a63/Hangman/Program.cs#L42

Often a Console.Clear on wrong place does delete too much information, especially when used in a loop. 

You could output the general information "Hangman Game" etc. before your loop once, and just leave the input tries etc. on screen. I like it more then having no information as user anymore ;)

**Comment by thirdiblind** [comment]
Good suggestion. Changes made and pushed.
