### ISSUE TITLE
Avoid duplicated code, use variables

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Hangman#13]
If you see something like this:
![image](https://github.com/thirdiblind/Hangman/assets/130921606/f6ab1dc4-1611-43aa-b908-ac480e8af76e)
This should be an direct hint to use a variable to store the current tries left and use it in the output then :) 

And please change this outputs and use string interpolation $ like in all other outputs too

**Comment by thirdiblind** [comment]
Great insight here. Replacing this with a variable.
