### ISSUE TITLE
Structuring if statements

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Hangman#14]
![image](https://github.com/thirdiblind/Hangman/assets/130921606/e0aabe2b-5cbf-400d-bd0a-70cfd5b444eb)
If you have a look on your code, you got nested if statements. Which is in general OK and you can not always avoid it :) But it is always easier to have less nested if statements, loops or whatever, as it makes code easier readable and understandable.

So what you could for example do here is, to change your if. Instead of first checking on the OK case, you could check if letter is contained, do your output and immediately do a "continue;" so in case the letter was already used, you just don't go further in loop at all.
```
  if (lettersGuessed.Contains(upperKeyChar))
  {
  Console.WriteLine($"You have " + (MAX_ATTEMPTS - incorrectTries) + $" attempts remaining. The letter {upperKeyChar} has already 
  been guessed! \n");
   continue;
}
```

So you would get rid of one nested if, as you not even need an else then, you can be sure that the code reached after that if is only executed in case the letter was not yet one of the used ones.

**Comment by thirdiblind** [comment]
This was challenging. Had to break code down into sections in order to make restructuring of code easier. Also added in comments to make more readable.
