### ISSUE TITLE
You can use constants for char values too

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Hangman#15]
https://github.com/thirdiblind/Hangman/blob/d987e7a49cec7976dfd62bf5137c8ffe8d387e74/Hangman/Program.cs#L35

I would recommend to use a constant for your placeholder character and the Y/N that user can enter too.

Especially later in larger projects, if you use characters like Y or N often, you should always go for an constant.

**Comment by thirdiblind** [comment]
Good points here. Issues resolved, pushing to repo.
