### ISSUE TITLE
Use conditions to store value to bool variable

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Hangman#16]
https://github.com/thirdiblind/Hangman/blob/d987e7a49cec7976dfd62bf5137c8ffe8d387e74/Hangman/Program.cs#L111-L114

This could be useful for the future, a simple way to store an boolean value to a variable , instead of always having an if statement like here would be, to directly use the condition and store it to the value:

So in your case, the gameActive should hold Y in case user enter Y, so you need to check if the user enter Y if so, the variable will get true as value, otherwise false. 

` gameActive = (replay == 'Y');`

**Comment by thirdiblind** [comment]
Good to know! Replaced if statement with this boolean conditional expression.
