### ISSUE TITLE
Do not create Random objects all time

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Hangman#17]
https://github.com/thirdiblind/Hangman/blob/d987e7a49cec7976dfd62bf5137c8ffe8d387e74/Hangman/Program.cs#L26

Again something that will get pretty relevant in next projects. You should avoid creating Random objects over and over again. Like currently, you will create a new Random object each time a game is started. 

Instead better define a Random object once at the beginning of your code and use it everywhere you need it. This could look like:

`public static readonly Random random = new Random();

public static void Main(string[] args)`

Random is something that leads often to errors if there exist to many of those objects in an application, therefore, better stick to one object. In larger projects you can even define it on a "global" position, so if you got more classes later on, you can use it from every class. One object is enought therefore :) But... will learn more about it later on

**Comment by thirdiblind** [comment]
Changes made and pushed to repo!
