### ISSUE TITLE
Move List outside the loop

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Hangman#18]
https://github.com/thirdiblind/Hangman/blob/d987e7a49cec7976dfd62bf5137c8ffe8d387e74/Hangman/Program.cs#L12-L22

This list holding the words to be guessed, is filled with fixed values, so move it outside the loop, it is not necessary to create a new list each loop iteration.

**Comment by thirdiblind** [comment]
Completed during fix #14
