### ISSUE TITLE
Keep correlated blocks together

### ISSUE THREAD

**Issue by incredibleLeitman** [thirdiblind/Hangman#7]
https://github.com/thirdiblind/Hangman/blob/61c289074f4bbc9fbaa1951cfce890e19be76cf3/Hangman/Program.cs#L9
https://github.com/thirdiblind/Hangman/blob/61c289074f4bbc9fbaa1951cfce890e19be76cf3/Hangman/Program.cs#L31

In c# there is no need to define all used variables on top, it helps readability when grouping things that belong together:

```c#
 int incorrectTries = 0; 
while (incorrectTries < MAX_ATTEMPTS)
```

**Comment by thirdiblind** [comment]
Correction made.
