### ISSUE TITLE
combine newlines into one WriteLineCall

### ISSUE THREAD

**Issue by incredibleLeitman** [thirdiblind/Hangman#8]
https://github.com/thirdiblind/Hangman/blob/61c289074f4bbc9fbaa1951cfce890e19be76cf3/Hangman/Program.cs#L58-L59

Instead of having a separate empty WriteLine call you could just use the newline operator at the end of your output:
```c#
Console.WriteLine("Correct! You have " + (MAX_ATTEMPTS - incorrectTries) + " attempts remaining.\n"); 
```

**Comment by thirdiblind** [comment]
Made correction.
