### ISSUE TITLE
Duplicate condition and finalized logic within the loop

### ISSUE THREAD

**Issue by incredibleLeitman** [thirdiblind/Hangman#9]
https://github.com/thirdiblind/Hangman/blob/61c289074f4bbc9fbaa1951cfce890e19be76cf3/Hangman/Program.cs#L68-L74
https://github.com/thirdiblind/Hangman/blob/61c289074f4bbc9fbaa1951cfce890e19be76cf3/Hangman/Program.cs#L77-L80

The condition for checking if the mysteryWord matches is kinda duplicated in your code, here you could use a flag instead to only once do this check.

Also, the output for "you loose" is after the loop (where it belongs :D) while the output for "you win" is within the loop: 
this should be combined and move to some common block which is way more maintainable: 

```c#
bool userHasWon = false;
while (incorrectTries < MAX_ATTEMPTS)
{
  ...
  
  if (user has guessed mysteryWord)
    // set the won flag to true and break
    userHasWon = true;
    break;
    
  // otherwise the user will exceed the amount of tries and the loop breaks
}

// handle the result of won or not after the loop
if (userHasWon)
  // output for won
else
  // user has lost
```

**Comment by thirdiblind** [comment]
Made correction.
